{
 "title": "LETV-MAS-OMP-DOCKERS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "letv_mas_docker_host",
    "label": "letv_mas_docker_host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "letv_mas_docker_container",
    "label": "letv_mas_docker_container",
    "query": "SHOW TAG VALUES WITH KEY = \"container_name\" WHERE host =~ /$letv_mas_docker_host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "container: cpu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu-usage" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]/[[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$letv_mas_docker_host$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$letv_mas_docker_container$/" }
     ]
    }
   ]
  },
  {
   "title": "container: mem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "mem-usage" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]/[[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$letv_mas_docker_host$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$letv_mas_docker_container$/" }
     ]
    }
   ]
  },
  {
   "title": "container: disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "disk-usage" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$letv_mas_docker_host$/" }
     ]
    }
   ]
  },
  {
   "title": "container: net",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "io-throughput" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]/[[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       { "params": [ "io_serviced_recursive_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$letv_mas_docker_host$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$letv_mas_docker_container$/" }
     ]
    }
   ]
  }
 ]
}