{
 "title": "LETV-MAS-OMP-BIZS",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "letv_mas_biz_name",
    "label": "letv_mas_biz_name",
    "query": "SHOW TAG VALUES WITH KEY = \"serviceName\""
   },
   {
    "name": "letv_mas_biz_host",
    "label": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"serviceIndex\" WHERE serviceName =~ /$letv_mas_biz_name$/"
   },
   {
    "name": "letv_mas_biz_uri",
    "label": "uri",
    "query": "SHOW TAG VALUES WITH KEY = \"uri\" WHERE serviceIndex =~ /$letv_mas_biz_host$/"
   },
   {
    "name": "letv_mas_biz_status",
    "label": "status",
    "query": "SHOW TAG VALUES WITH KEY = \"status\" WHERE serviceIndex =~ /$letv_mas_biz_host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "jvm: mem/thread",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes", "label": "mem" }
   ],
   "targets": [
    {
     "alias": "mem([[tag_serviceIndex]])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "serviceIndex" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "serviceName", "operator": "=~", "value": "/^$letv_mas_biz_name$/" },
      { "condition": "AND", "key": "serviceIndex", "operator": "=~", "value": "/^$letv_mas_biz_host$/" }
     ]
    },
    {
     "alias": "thread([[tag_serviceIndex]])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "serviceIndex" ], "type": "tag" }
     ],
     "measurement": "jvm_threads_live",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "serviceName", "operator": "=~", "value": "/^$letv_mas_biz_name$/" },
      { "condition": "AND", "key": "serviceIndex", "operator": "=~", "value": "/^$letv_mas_biz_host$/" }
     ]
    }
   ]
  },
  {
   "title": "system: cpu/load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit", "label": "cpu" }
   ],
   "targets": [
    {
     "alias": "cpu([[tag_serviceIndex]])",
     "groupBy": [
      { "params": [ "serviceIndex" ], "type": "tag" }
     ],
     "measurement": "system_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serviceName", "operator": "=~", "value": "/^$letv_mas_biz_name$/" },
      { "condition": "AND", "key": "serviceIndex", "operator": "=~", "value": "/^$letv_mas_biz_host$/" }
     ]
    },
    {
     "alias": "load([[tag_serviceIndex]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "serviceIndex" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_load_average_1m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "serviceName", "operator": "=~", "value": "/^$letv_mas_biz_name$/" },
      { "condition": "AND", "key": "serviceIndex", "operator": "=~", "value": "/^$letv_mas_biz_host$/" }
     ]
    }
   ]
  },
  {
   "title": "service: requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "[[tag_serviceIndex]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "serviceIndex" ], "type": "tag" }
     ],
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "serviceName", "operator": "=~", "value": "/^$letv_mas_biz_name$/" },
      { "condition": "AND", "key": "serviceIndex", "operator": "=~", "value": "/^$letv_mas_biz_host$/" },
      { "condition": "AND", "key": "uri", "operator": "=~", "value": "/^$letv_mas_biz_uri$/" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$letv_mas_biz_status$/" }
     ]
    }
   ]
  },
  {
   "title": "service: status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_status]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "serviceName", "operator": "=~", "value": "/^$letv_mas_biz_name$/" },
      { "condition": "AND", "key": "serviceIndex", "operator": "=~", "value": "/^$letv_mas_biz_host$/" },
      { "condition": "AND", "key": "uri", "operator": "=~", "value": "/^$letv_mas_biz_uri$/" }
     ]
    }
   ]
  },
  {
   "title": "stream/bus: err/ok",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "err-[[tag_channel]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "spring_integration_channel_sendErrors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "serviceName", "operator": "=~", "value": "/^$letv_mas_biz_name$/" },
      { "condition": "AND", "key": "serviceIndex", "operator": "=~", "value": "/^$letv_mas_biz_host$/" }
     ]
    },
    {
     "alias": "ok-[[tag_channel]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "spring_integration_channel_sends",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "serviceName", "operator": "=~", "value": "/^$letv_mas_biz_name$/" },
      { "condition": "AND", "key": "serviceIndex", "operator": "=~", "value": "/^$letv_mas_biz_host$/" }
     ]
    }
   ]
  },
  {
   "title": "service: status(40x、50x)",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serviceName", "operator": "=~", "value": "/^$letv_mas_biz_name$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "400" },
      { "condition": "OR", "key": "status", "operator": "=", "value": "500" },
      { "condition": "OR", "key": "status", "operator": "=", "value": "404" }
     ]
    }
   ]
  }
 ]
}